# Generated by Django 4.2.x on 2026-06-23 17:20
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # ✅ ከቀዳሚው (0014) ማይግሬሽን ጋር በደህንነት አስተሳስረነዋል
        ('marketplace', '0014_add_product_and_fields_to_vectormemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteregistry',
            name='competitor_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='siteregistry',
            name='primary_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='siteregistry',
            name='pending_notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]